### ISSUE TITLE
An error occurred while transfer

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#4127]
version：mainnet-1.0.2.2
os：centos7
In the transaction between accounts, the following error message appears

![image](https://user-images.githubusercontent.com/9130123/41459170-50ee97ae-70bb-11e8-960e-526aac3b2f97.png)

This is the plug-in that I started:
plugin = eosio::chain_api_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
plugin = eosio::chain_plugin
plugin = eosio::http_plugin
plugin = eosio::producer_plugin

**Comment by jgiszczak** [comment]
A problem with premature transaction expiration was corrected in today's 1.0.4 release.  Please update and try again.

**Comment by ddzyan** [comment]
I've done that, but the problem remains.
version：mainnet-1.0.5
os：centos7
![image](https://user-images.githubusercontent.com/9130123/41700326-64c8dcf0-755a-11e8-9bbd-64635a450542.png)
