### ISSUE TITLE
Macos 10.13.5 mongodb compile failed ...

### ISSUE THREAD

**Issue by dextree** [EOSIO/eos#4830]
I don't know why my mongodb is not installing....

`
	~/eos> ./eosio_build.sh

	Beginning build version: 1.2
	2018年 7月24日 星期二 10时45分33秒 UTC
	User: karpedm
	git head id: 75635168e743c3e65bb6345a1eaedd905581e6b0
	Current branch: master

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.5
	CPU speed: 2.30Ghz
	CPU cores: 4
	Physical Memory: 8 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 233G
	Disk space available: 32G

	Checking xcode-select installation
	xcode-select installation found @ 
	/usr/bin/xcode-select 

	Checking Ruby installation.
	Ruby installation found @ 
	/usr/local/bin/ruby 

	Checking Home Brew installation
	Home Brew installation found @
	/usr/local/bin/brew

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking LCOV ... 		 LCOV found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking boost library installation.
	Boost 1.67.0 found at /usr/local.

	Checking MongoDB C++ driver installation.
	Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   617    0   617    0     0    427      0 --:--:--  0:00:01 --:--:--   427
	100 6193k  100 6193k    0     0   196k      0  0:00:31  0:00:31 --:--:--  295k
	-- The C compiler identification is ;AppleClang 9.1.0.9020039
	-- Check for working C compiler: 	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
	-- Check for working C compiler: 	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works	
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	  -- Using bundled libbson
	libbson version (from VERSION_CURRENT file): 1.10.2
	-- Check if the system is big endian
	-- Searching 16 bit integer
	-- Looking for sys/types.h
	-- Looking for sys/types.h - found
	-- Looking for stdint.h
	-- Looking for stdint.h - found
	-- Looking for stddef.h
	-- Looking for stddef.h - found
	-- Check size of unsigned short
	-- Check size of unsigned short - done
	-- Using unsigned short
	-- Check if the system is big endian - little endian
	-- Looking for snprintf
	-- Looking for snprintf - found
	-- Looking for reallocf
	-- Looking for reallocf - found
	-- Performing Test BSON_HAVE_TIMESPEC
	-- Performing Test BSON_HAVE_TIMESPEC - Success
	--     struct timespec found
	-- Looking for gmtime_r
	-- Looking for gmtime_r - found
	-- Looking for rand_r
	-- Looking for rand_r - found
	-- Looking for strings.h
	-- Looking for strings.h - found
	-- Looking for clock_gettime
	-- Looking for clock_gettime - found
	-- Looking for strnlen
	-- Looking for strnlen - found
	-- Looking for stdbool.h
	-- Looking for stdbool.h - found
	-- Looking for SYS_gettid
	-- Looking for SYS_gettid - found
	-- Looking for syscall
	-- Looking for syscall - found
	-- Performing Test HAVE_ATOMIC_32_ADD_AND_FETCH
	-- Performing Test HAVE_ATOMIC_32_ADD_AND_FETCH - Success
	-- Performing Test HAVE_ATOMIC_64_ADD_AND_FETCH
	-- Performing Test HAVE_ATOMIC_64_ADD_AND_FETCH - Success
	CMake Deprecation Warning at src/libbson/CMakeLists.txt:148 (cmake_policy):
	  The OLD behavior for policy CMP0042 will be removed from a future version
	  of CMake.

	  The cmake-policies(7) manual explains that the OLD behaviors of all
	  policies are deprecated and that a policy should be set to OLD only under
	  specific short-term circumstances.  Projects should be ported to the NEW
	  behavior and not rely on setting a policy to OLD.

	-- Looking for pthread.h
	-- Looking for pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - found
	-- Found Threads: TRUE  
	libmongoc version (from VERSION_CURRENT file): 1.10.2
	-- Searching for zlib CMake packages
	-- Found ZLIB: /usr/local/lib/libz.dylib (found version "1.2.8") 
	--   zlib found version "1.2.8"
	--   zlib include path "/usr/local/include"
	--   zlib libraries "/usr/local/lib/libz.dylib"
	-- Looking for include file unistd.h
	-- Looking for include file unistd.h - found
	-- Looking for include file stdarg.h
	-- Looking for include file stdarg.h - found
	-- Searching for sasl/sasl.h
	--   Found in /usr/include
	-- Searching for libsasl2
	--   Found /usr/lib/libsasl2.dylib
	-- Check size of socklen_t
	-- Check size of socklen_t - done
	-- Looking for res_nsearch
	-- Looking for res_nsearch - found
	-- Looking for res_ndestroy
	-- Looking for res_ndestroy - found
	-- Looking for sched_getcpu
	-- Looking for sched_getcpu - not found
	-- Detected parameters: accept (int, struct sockaddr *, socklen_t *)
	-- Searching for compression library header snappy-c.h
	--   Found in /usr/local/include
	-- Searching for libsnappy
	--   Found /usr/local/lib/libsnappy.a
	-- Compiling against Secure Transport
	-- Compiling against Cyrus SASL
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /tmp/mongo-c-driver-1.10.2/cmake-build
	Scanning dependencies of target bson_static
	Scanning dependencies of target bson_shared
	[  0%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bcon.c.o
	[  0%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson.c.o
	[  1%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bcon.c.o
	[  1%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson.c.o
	[  1%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-atomic.c.o
	[  2%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-atomic.c.o
	[  2%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-clock.c.o
	[  2%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-clock.c.o
	[  2%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-context.c.o
	[  2%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-context.c.o
	[  3%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-decimal128.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-decimal128.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-error.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-error.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-iso8601.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-iso8601.c.o
	[  4%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-iter.c.o
	[  5%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-iter.c.o
	[  5%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-json.c.o
	[  6%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-json.c.o
	[  6%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-keys.c.o
	[  6%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-keys.c.o
	[  6%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-md5.c.o
	[  6%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-md5.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-memory.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-memory.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-oid.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-oid.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-reader.c.o
	[  8%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-reader.c.o
	[  9%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-string.c.o
	[  9%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-string.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-timegm.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-timegm.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-utf8.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-utf8.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-value.c.o
	[ 10%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-value.c.o
	[ 11%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-version-functions.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-version-functions.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/bson/bson-writer.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/jsonsl/jsonsl.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_static.dir/src/bson/bson-writer.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_shared.dir/src/jsonsl/jsonsl.c.o
	[ 12%] Building C object src/libbson/CMakeFiles/bson_static.dir/__/common/common-b64.c.o
	[ 13%] Building C object src/libbson/CMakeFiles/bson_shared.dir/__/common/common-b64.c.o
	[ 14%] Linking C shared library libbson-1.0.dylib
	[ 14%] Linking C static library libbson-static-1.0.a
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbson-static-1.0.a(bson-atomic.c.o) has no symbols
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbson-static-1.0.a(bson-atomic.c.o) has no symbols
	[ 14%] Built target bson_static
	[ 14%] Built target bson_shared
	Scanning dependencies of target mongoc_static
	Scanning dependencies of target bson-streaming-reader
	Scanning dependencies of target json-to-bson
	Scanning dependencies of target bson-to-json
	[ 14%] Building C object src/libbson/CMakeFiles/bson-to-json.dir/examples/bson-to-json.c.o
	[ 14%] Building C object src/libbson/CMakeFiles/json-to-bson.dir/examples/json-to-bson.c.o
	[ 15%] Building C object src/libbson/CMakeFiles/bson-streaming-reader.dir/examples/bson-streaming-reader.c.o
	[ 15%] Linking C executable bson-to-json
	[ 15%] Linking C executable json-to-bson
	[ 15%] Linking C executable bson-streaming-reader
	[ 15%] Built target bson-to-json
	[ 15%] Built target json-to-bson
	[ 15%] Built target bson-streaming-reader
	Scanning dependencies of target bcon-speed
	Scanning dependencies of target bson-metrics
	Scanning dependencies of target bcon-col-view
	[ 15%] Building C object src/libbson/CMakeFiles/bcon-speed.dir/examples/bcon-speed.c.o
	[ 15%] Building C object src/libbson/CMakeFiles/bson-metrics.dir/examples/bson-metrics.c.o
	[ 15%] Building C object src/libbson/CMakeFiles/bcon-col-view.dir/examples/bcon-col-view.c.o
	[ 16%] Linking C executable bcon-speed
	[ 16%] Linking C executable bcon-col-view
	[ 16%] Linking C executable bson-metrics
	[ 16%] Built target bcon-speed
	[ 16%] Built target bcon-col-view
	Scanning dependencies of target bson-validate
	Scanning dependencies of target mongoc_shared
	[ 16%] Built target bson-metrics
	[ 17%] Building C object src/libbson/CMakeFiles/bson-validate.dir/examples/bson-validate.c.o
	[ 17%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-apm.c.o
	[ 18%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-array.c.o
	[ 18%] Linking C executable bson-validate
	[ 18%] Built target bson-validate
	[ 18%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-async.c.o
	[ 18%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-async-cmd.c.o
	[ 18%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-buffer.c.o
	[ 19%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-bulk-operation.c.o
	[ 19%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-change-stream.c.o
	[ 19%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-client.c.o
	[ 19%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-apm.c.o
	[ 20%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-client-pool.c.o
	[ 20%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-array.c.o
	[ 20%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cluster.c.o
	[ 20%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-async.c.o
	[ 21%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-async-cmd.c.o
	[ 21%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-buffer.c.o
	[ 21%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-collection.c.o
	[ 21%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-compression.c.o
	[ 21%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-bulk-operation.c.o
	[ 22%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-change-stream.c.o
	[ 22%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-client.c.o
	[ 23%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-client-pool.c.o
	[ 23%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-counters.c.o
	[ 23%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cluster.c.o
	[ 23%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-array.c.o
	[ 23%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor.c.o
	[ 24%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-cmd.c.o
	[ 25%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-collection.c.o
	[ 25%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-compression.c.o
	[ 25%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-cmd-deprecated.c.o
	[ 25%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-counters.c.o
	[ 25%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-find.c.o
	[ 26%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-array.c.o
	[ 26%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor.c.o
	[ 26%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-find-cmd.c.o
	[ 27%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-find-opquery.c.o
	[ 27%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cursor-legacy.c.o
	[ 27%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-cmd.c.o
	[ 27%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-cmd-deprecated.c.o
	[ 27%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-database.c.o
	[ 28%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-find-and-modify.c.o
	[ 29%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-find.c.o
	[ 29%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-find-cmd.c.o
	[ 29%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-find-opquery.c.o
	[ 29%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-init.c.o
	[ 29%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-gridfs.c.o
	[ 30%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cursor-legacy.c.o
	[ 30%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-gridfs-file.c.o
	[ 30%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-database.c.o
	[ 30%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-find-and-modify.c.o
	[ 31%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-gridfs-file-list.c.o
	[ 31%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-gridfs-file-page.c.o
	[ 31%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-init.c.o
	[ 32%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-gridfs.c.o
	[ 32%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-gridfs-file.c.o
	[ 32%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-handshake.c.o
	[ 33%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-host-list.c.o
	[ 33%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-index.c.o
	[ 33%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-gridfs-file-list.c.o
	[ 34%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-gridfs-file-page.c.o
	[ 34%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-list.c.o
	[ 34%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-linux-distro-scanner.c.o
	[ 34%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-handshake.c.o
	[ 35%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-log.c.o
	[ 35%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-host-list.c.o
	[ 35%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-matcher.c.o
	[ 35%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-matcher-op.c.o
	[ 35%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-index.c.o
	[ 36%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-list.c.o
	[ 37%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-memcmp.c.o
	[ 37%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cmd.c.o
	[ 37%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-linux-distro-scanner.c.o
	[ 37%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-log.c.o
	[ 37%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-opts.c.o
	[ 38%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-matcher.c.o
	[ 38%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-opts-helpers.c.o
	[ 38%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-matcher-op.c.o
	[ 39%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-queue.c.o
	[ 39%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-memcmp.c.o
	[ 39%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cmd.c.o
	[ 39%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-read-concern.c.o
	[ 39%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-read-prefs.c.o
	[ 40%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-rpc.c.o
	[ 41%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-opts.c.o
	[ 41%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-server-description.c.o
	[ 41%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-opts-helpers.c.o
	[ 41%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-server-stream.c.o
	[ 41%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-queue.c.o
	[ 42%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-read-concern.c.o
	[ 42%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-read-prefs.c.o
	[ 42%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-client-session.c.o
	[ 42%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-rpc.c.o
	[ 42%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-server-description.c.o
	[ 43%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-set.c.o
	[ 44%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-server-stream.c.o
	[ 44%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-socket.c.o
	[ 44%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-buffered.c.o
	[ 45%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream.c.o
	[ 45%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-client-session.c.o
	[ 45%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-set.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-socket.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-file.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-gridfs.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-socket.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-buffered.c.o
	[ 46%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream.c.o
	[ 47%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-topology.c.o
	[ 47%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-file.c.o
	[ 47%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-topology-description.c.o
	[ 47%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-topology-description-apm.c.o
	[ 48%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-gridfs.c.o
	[ 48%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-socket.c.o
	[ 48%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-topology.c.o
	[ 49%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-topology-scanner.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-topology-description.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-uri.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-util.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-topology-description-apm.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-version-functions.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-topology-scanner.c.o
	[ 50%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-uri.c.o
	[ 51%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-util.c.o
	[ 52%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-write-command.c.o
	[ 52%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-write-command-legacy.c.o
	[ 52%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-version-functions.c.o
	[ 52%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-write-concern.c.o
	[ 52%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-write-command.c.o
	[ 53%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/__/common/common-b64.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-write-command-legacy.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-write-concern.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-crypto.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/__/common/common-b64.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-crypto.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-scram.c.o
	[ 54%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-tls.c.o
	[ 55%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-ssl.c.o
	[ 56%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-scram.c.o
	[ 56%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-tls.c.o
	[ 56%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-ssl.c.o
	[ 56%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-crypto-common-crypto.c.o
	[ 56%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-rand-common-crypto.c.o
	[ 57%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-crypto-common-crypto.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-stream-tls-secure-transport.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-secure-transport.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-rand-common-crypto.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cluster-sasl.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-stream-tls-secure-transport.c.o
	[ 58%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-secure-transport.c.o
	[ 59%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cluster-sasl.c.o
	[ 59%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-sasl.c.o
	[ 60%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cluster-cyrus.c.o
	[ 60%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-sasl.c.o
	[ 60%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-cyrus.c.o
	[ 60%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cluster-cyrus.c.o
	[ 61%] Building C object src/libmongoc/CMakeFiles/mongoc_shared.dir/src/mongoc/mongoc-cyrus.c.o
	[ 61%] Linking C static library libmongoc-static-1.0.a
	[ 61%] Linking C shared library libmongoc-1.0.dylib
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmongoc-static-1.0.a(mongoc-linux-distro-scanner.c.o) has no symbols
	Undefined symbols for architecture x86_64:
	  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  void std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::__push_back_slow_path<snappy::SnappySinkAllocator::Datablock const>(snappy::SnappySinkAllocator::Datablock const&) in libsnappy.a(snappy.cc.o)
		  void std::__1::vector<char*, std::__1::allocator<char*> >::__push_back_slow_path<char* const>(char* const&) in libsnappy.a(snappy.cc.o)
	  "std::logic_error::logic_error(char const*)", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "std::length_error::~length_error()", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::resize(unsigned long, char)", referenced from:
		  snappy::STLStringResizeUninitialized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, unsigned long) in libsnappy.a(snappy.cc.o)
		  snappy::Compress(char const*, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in libsnappy.a(snappy.cc.o)
	  "std::terminate()", referenced from:
		  ___clang_call_terminate in libsnappy.a(snappy.cc.o)
	  "typeinfo for std::length_error", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "vtable for __cxxabiv1::__class_type_info", referenced from:
		  typeinfo for snappy::Sink in libsnappy.a(snappy-sinksource.cc.o)
		  typeinfo for snappy::Source in libsnappy.a(snappy-sinksource.cc.o)
	  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
	  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
		  typeinfo for snappy::ByteArraySource in libsnappy.a(snappy-sinksource.cc.o)
		  typeinfo for snappy::UncheckedByteArraySink in libsnappy.a(snappy-sinksource.cc.o)
	  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
	  "vtable for std::length_error", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
	  "operator delete[](void*)", referenced from:
		  snappy::Compress(snappy::Source*, snappy::Sink*) in libsnappy.a(snappy.cc.o)
		  snappy::internal::WorkingMemory::~WorkingMemory() in libsnappy.a(snappy.cc.o)
		  snappy::SnappySinkAllocator::Deleter(void*, char const*, unsigned long) in libsnappy.a(snappy.cc.o)
	  "operator delete(void*)", referenced from:
		  std::__1::__vector_base<char*, std::__1::allocator<char*> >::~__vector_base() in libsnappy.a(snappy.cc.o)
		  std::__1::__vector_base<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::~__vector_base() in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::~__split_buffer() in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::~__split_buffer() in libsnappy.a(snappy.cc.o)
		  snappy::ByteArraySource::~ByteArraySource() in libsnappy.a(snappy-sinksource.cc.o)
		  snappy::UncheckedByteArraySink::~UncheckedByteArraySink() in libsnappy.a(snappy-sinksource.cc.o)
	  "operator new[](unsigned long)", referenced from:
		  snappy::internal::WorkingMemory::GetHashTable(unsigned long, int*) in libsnappy.a(snappy.cc.o)
		  snappy::Compress(snappy::Source*, snappy::Sink*) in libsnappy.a(snappy.cc.o)
		  snappy::SnappySinkAllocator::Allocate(int) in libsnappy.a(snappy.cc.o)
	  "operator new(unsigned long)", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "___cxa_allocate_exception", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "___cxa_begin_catch", referenced from:
		  ___clang_call_terminate in libsnappy.a(snappy.cc.o)
	  "___cxa_free_exception", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "___cxa_pure_virtual", referenced from:
		  vtable for snappy::Sink in libsnappy.a(snappy-sinksource.cc.o)
		  vtable for snappy::Source in libsnappy.a(snappy-sinksource.cc.o)
	  "___cxa_throw", referenced from:
		  std::__1::vector<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock> >::allocate(unsigned long) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<snappy::SnappySinkAllocator::Datablock, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<snappy::SnappySinkAllocator::Datablock>&) in libsnappy.a(snappy.cc.o)
		  std::__1::__split_buffer<char*, std::__1::allocator<char*>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<char*>&) in libsnappy.a(snappy.cc.o)
	  "___gxx_personality_v0", referenced from:
		  snappy::GetUncompressedLength(snappy::Source*, unsigned int*) in libsnappy.a(snappy.cc.o)
		  snappy::Compress(snappy::Source*, snappy::Sink*) in libsnappy.a(snappy.cc.o)
		  snappy::RawUncompressToIOVec(char const*, unsigned long, iovec const*, unsigned long) in libsnappy.a(snappy.cc.o)
		  bool snappy::InternalUncompress<snappy::SnappyIOVecWriter>(snappy::Source*, snappy::SnappyIOVecWriter*) in libsnappy.a(snappy.cc.o)
		  snappy::RawUncompress(char const*, unsigned long, char*) in libsnappy.a(snappy.cc.o)
		  bool snappy::InternalUncompress<snappy::SnappyArrayWriter>(snappy::Source*, snappy::SnappyArrayWriter*) in libsnappy.a(snappy.cc.o)
		  snappy::IsValidCompressedBuffer(char const*, unsigned long) in libsnappy.a(snappy.cc.o)
		  ...
	ld: symbol(s) not found for architecture x86_64
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	make[2]: *** [src/libmongoc/libmongoc-1.0.0.0.0.dylib] Error 1
	make[1]: *** [src/libmongoc/CMakeFiles/mongoc_shared.dir/all] Error 2
	make[1]: *** Waiting for unfinished jobs....
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmongoc-static-1.0.a(mongoc-linux-distro-scanner.c.o) has no symbols
	[ 61%] Built target mongoc_static
	make: *** [all] Error 2
		Error compiling MongoDB C driver.
		Exiting now.`

**Comment by jingzhehu** [comment]
I've encountered the problem before. Running `./scripts/clean_old_install.sh` should resolve the issue.

**Comment by halsaphi** [comment]
If Running ./scripts/clean_old_install.sh did not work please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
