### ISSUE TITLE
core_symbol does not exist

### ISSUE THREAD

**Issue by muskaninnotical** [EOSIO/eos#5443]
In file included from /home/innotical/Desktop/test/test.cpp:1:
In file included from /home/innotical/Desktop/test/test.hpp:1:
/home/innotical/Desktop/eos/contracts/eosiolib/asset.hpp:59:54: error: use of undeclared
      identifier 'SYS'
      explicit asset( int64_t a = 0, symbol_type s = CORE_SYMBOL )
                                                     ^
/home/innotical/Desktop/eos/contracts/eosiolib/core_symbol.hpp:7:26: note: expanded from macro
      'CORE_SYMBOL'
#define CORE_SYMBOL SY(4,SYS)
                         ^
1 error generated.
Error while processing /home/innotical/Desktop/test/test.cpp.

**Comment by xJonathanLEI** [comment]
Please see this for the solution: #5401 

Hey guy could you just please **merge it**? People have been complaining for days. It's just a one line code change. How hard is it? It's been 4 days!

**Comment by jgiszczak** [comment]
This has been corrected since version 1.2.0.  Update your github checkout to the most recent release.

**Comment by xJonathanLEI** [comment]
Like I said, please follow the PR #5401 to solve this issue.

Or, as they've finally merged the PR, you may now use the `release/1.2.x` branch instead:

    $ git checkout release/1.2.x

**Comment by yyh1102** [comment]
@xJonathanLEI i've pull the latest branch, both `develop` and `release/1.2.x`, but still throws the error.

**Comment by yyh1102** [comment]
when building EOS, it still throws like below:
![image](https://user-images.githubusercontent.com/10328169/44943268-13c46c00-adf6-11e8-8275-c9ca4c5122bd.png)

**Comment by jgiszczak** [comment]
You do need to rerun CMake yourself if you're not using the build script.  The `eosiocpp` tool must be regenerated for the changes to take effect.  Simply running `make` is not sufficient.

**Comment by yyh1102** [comment]
@jgiszczak i use `eosio_build.sh` to run the build process, but it still failed~

**Comment by jgiszczak** [comment]
@yyh1102 Verify `eos/build/contracts/eosiolib/core_symbol.hpp` exists and looks like this:
```c++
/** @file 
 *    @copyright defined in eos/LICENSE.txt 
 *
 * \warning This file is machine generated. DO NOT EDIT.  See core_symbol.hpp.in for changes.
 */

#define CORE_SYMBOL S(4,SYS)
```
