### ISSUE TITLE
STAT-206 ⁃ Local eosd can't sync with the testnet

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#792]
Got the following error:

```javascript
878174ms thread-0   net_plugin.cpp:1327           handle_message       ] Peer network version does not match expected -5408 but got -8530
```

Furthermore, the server_version of the testnet is `0d3adeae` while the server_version of my local node in mac is `d3adeae0`. Even though both of the testnet and my local node is in branch `STAT-2017-11-25` which has commit hash `d3adeae0d895fe186c624fac992c40eb359902a3`

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Jonathan, what would cause the same hash to be truncated differently?

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

From git documentation:

{quote}core.abbrev
Set the length object names are abbreviated to. If unspecified or set to "auto", an appropriate value is computed based on the approximate number of packed objects in your repository, which hopefully is enough for abbreviated object names to stay unique for some time. The minimum length is 4.
{quote}
The output of that algorithm is specific to the state of the local repository.  A very large repository results in more digits than a smaller one.

The solution is to specify the truncation length in the command executed by cmake.

**Comment by heifner** [comment]
Resolved by #793

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Will be in post tag: STAT-2017-11-27

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

On STAT-2017-11-27, the issue still persists
Testnet version = 0ccd29bb
Local Mac version = ccd29bbd
Git Tag = ccd29bbd6ed40459ef30a7b0e9f40c6ea60bf60a

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Testnet does not yet have the updated version of the code.  Will transition this ticket back to QA after the next tag.

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Gotcha

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Version number is updated now. However, another sync problem appears after that
 !Screen Shot 2017-11-30 at 1.59.47 PM.png|thumbnail! 

I have attached my config here too [^config.ini] and I'm using genesis from STAT-48

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

I'm going to create new JIRA for this
