### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by apporc** [EOSIO/eos#94]
eos/libraries/wasm-jit/Source/WASM/WASMSerialization.cpp:543:17: error: uninitialized variable ‘returnType’ in ‘constexpr’ function        
      ResultType returnType;

This is master version.

**Comment by alexpmorris** [comment]
I got through that part @apporc so maybe that issue's been corrected in the latest pull, though I initiated the build from the included Docker config:

```[ 66%] Building CXX object libraries/wasm-jit/Source/WASM/CMakeFiles/WASM.dir/WASMSerialization.cpp.o```

However, I later got this error at 82%.  I'm using the latest pull *(again, attempting to build from docker)*:

```[ 82%] Building CXX object libraries/native_contract/CMakeFiles/eos_native_contract.dir/eos_contract.cpp.o
In file included from /tmp/eos/libraries/native_contract/staked_balance_contract.cpp:3:
/tmp/eos/libraries/native_contract/include/eos/native_contract/producer_objects.hpp:49:64: error: no viable conversion from returned value of type 'tuple<const long &, const chainbase::oid<native::staked::ProducerVotesObject> &>' to function return type 'pair<types::ShareType, id_type>' (aka 'pair<long, oid<native::staked::ProducerVotesObject> >')
   pair<types::ShareType,id_type> getVoteOrder()const { return std::tie( race.speed, id ); }
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

On another note, I've gotta say I've had a hell of a time getting either bitshares-core or eos working in a way that is easy to debug.  It started with me trying to track a nasty bitshares-core issue that's come up.  Couldn't get it to compile in Visual Studio 2013, and VS 2015 always gives me a bunch of these errors *(tried following the "official" Windows/bitshares-core howto wikis for both versions)*:

```Severity	Code	Description	Project	File	Line	Suppression State
Error	C2027	use of undefined type 'std::_Get_function_impl<_Fty>'	graphene_app	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional	472	
```
I did get bitshares-core to compile in ubuntu and CodeBlocks using CMake with CodeBlocks target, but not in a way that I could step through the code and debug.  Was going to try CodeLight or NetBeans next, though perhaps I'm just missing something silly.  Biggest problem is how long each build is taking if a single thing appears off, so it's been really tough experimenting.

I figure if I can get bitshares-core easy to debug in an IDE *(which *should* be an easier codebase to deal with than eos)*, then it should be relatively straight-forward to get eos setup in a similar fashion.

**Comment by jcalfee** [comment]
work-around: https://github.com/EOSIO/eos/commit/a97251d323280b51e9380d99a32d05a4db18a50a#commitcomment-23269248

**Comment by jcalfee** [comment]
Speaking of build errors .. Anyone seen this in the eos build?
```c++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I found this variable and re-created my "out of source" build using `cmake -DCMAKE_SHARED_LINKER_FLAGS=-v ...` .. Still can't build target eosd. I'm still clueless.

**Comment by jcalfee** [comment]
@apporc for reference you might want to try the Docker build.  It can help narrow down the issue.  However at the moment even the docker will fail on references to `std::tie` .. It can still provide a clue if you can get further using Docker.

**Comment by alexpmorris** [comment]
not sure about that other error James *(perhaps a double reference somewhere?)*, also a clean build *may* help (though I imagine you've tried that already).  

The Docker build appears to be working again too, built it without issue this time after a fresh git pull!  Just a few quick notes:

* Be aware of all the other exited dead containers that may have been left behind in past failed build attempts  (`docker ps -a`).  

* You can shell into the eos container using: `docker exec -it <containerIdOrName> bash` - eos container is likely called docker_eos_1, first created after calling `docker-compose` .

* Regarding bitshares, not sure what I was doing wrong with CodeBlocks, but I did mange to get bitshares-core running and debugging pretty much my first attempt in CodeLite!

**Comment by tinglany** [comment]
I  got the following error while make :
libraries/chain/CMakeFiles/eos_chain.dir/build.make:62: recipe for target 'libraries/chain/CMakeFiles/eos_chain.dir/chain_controller.cpp.o' failed
make[2]: *** [libraries/chain/CMakeFiles/eos_chain.dir/chain_controller.cpp.o] Error 1
CMakeFiles/Makefile2:1082: recipe for target 'libraries/chain/CMakeFiles/eos_chain.dir/all' failed
make[1]: *** [libraries/chain/CMakeFiles/eos_chain.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by heifner** [comment]
This is an old build issue that has been fixed. Also the Docker build has been enhanced greatly since this issue was created. Closing.
